on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

name: Build

jobs:
  create-boot-image:
    name: Create boot image for a30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build Mu
        run: |
          sudo apt update
          chmod 744 ./setup_env.sh
          ./setup_env.sh -p apt
          chmod 744 ./build_uefi.sh
          ./build_uefi.sh -d a30 -m 2 -r DEBUG
      - uses: actions/upload-artifact@v4
        with:
          name: Samsung Galaxy A30
          path: ./Mu-a30.tar
